{
  inputs,
  system,
  ...
}:
with inputs.nix-vscode-extensions.extensions.${system}.vscode-marketplace; [
  johnnymorganz.luau-lsp
  anderseandersen.html-class-suggestions
  astro-build.astro-vscode
  asvetliakov.vscode-neovim
  bbenoist.nix
  bernardogualberto.solidjs
  britesnow.vscode-toggle-quotes
  christian-kohler.npm-intellisense
  christian-kohler.path-intellisense
  dbaeumer.vscode-eslint
  donjayamanne.python-environment-manager
  esbenp.prettier-vscode
  formulahendry.auto-close-tag
  formulahendry.auto-rename-tag
  foxundermoon.shell-format
  helixquar.randomeverything
  jock.svg
  kamadorueda.alejandra
  kastorcode.kastorcode-dark-purple-theme
  kevinrose.vsc-python-indent
  mads-hartmann.bash-ide-vscode
  mgesbert.python-path
  mikestead.dotenv
  mkhl.direnv
  mohsen1.prettify-json
  mrmlnc.vscode-scss
  ms-python.python
  charliermarsh.ruff
  oderwat.indent-rainbow
  patbenatar.advanced-new-file
  pranaygp.vscode-css-peek
  redhat.vscode-yaml
  sibiraj-s.vscode-scss-formatter
  simonsiefke.svg-preview
  sleistner.vscode-fileutils
  solnurkarim.html-to-css-autocompletion
  steoates.autoimport
  sumneko.lua
  tamasfe.even-better-toml
  timonwong.shellcheck
  usernamehw.errorlens
  vscode-icons-team.vscode-icons
  vunguyentuan.vscode-css-variables
  tobias-z.vscode-harpoon
  johnnymorganz.stylua
]
